version: '3.9'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - ./env
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db
        networks:
            - app

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:app/frontend
        depends_on:
            - backend
        networks:
            - app
    db:
        image: mysql:5.7.22
        networks:
            - app
        container_name: db
        ports:
            - "5432:5432"
        environment:
            MYSQL_DATABASE: 'auth'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - pgdata:/var/lib/postgres/data

networks:
    app:
        driver: bridge

